"""Países para a pergunta de localização (chave = código ISO 3166-1 alfa-3 em minúsculas).

Gerado a partir do pycountry e do Babel. São 249 países e territórios; com as opções
'global' e 'nao_informado', a pergunta fica com 251 opções — abaixo do limite de 255 do Choice.
"""

PAISES = {
    'abw': ('Aruba', 'Aruba'),
    'afg': ('Afghanistan', 'Afeganistão'),
    'ago': ('Angola', 'Angola'),
    'aia': ('Anguilla', 'Anguila'),
    'ala': ('Åland Islands', 'Ilhas Aland'),
    'alb': ('Albania', 'Albânia'),
    'and': ('Andorra', 'Andorra'),
    'are': ('United Arab Emirates', 'Emirados Árabes Unidos'),
    'arg': ('Argentina', 'Argentina'),
    'arm': ('Armenia', 'Armênia'),
    'asm': ('American Samoa', 'Samoa Americana'),
    'ata': ('Antarctica', 'Antártida'),
    'atf': ('French Southern Territories', 'Territórios Franceses do Sul'),
    'atg': ('Antigua and Barbuda', 'Antígua e Barbuda'),
    'aus': ('Australia', 'Austrália'),
    'aut': ('Austria', 'Áustria'),
    'aze': ('Azerbaijan', 'Azerbaijão'),
    'bdi': ('Burundi', 'Burundi'),
    'bel': ('Belgium', 'Bélgica'),
    'ben': ('Benin', 'Benin'),
    'bes': ('Bonaire, Sint Eustatius and Saba', 'Países Baixos Caribenhos'),
    'bfa': ('Burkina Faso', 'Burquina Faso'),
    'bgd': ('Bangladesh', 'Bangladesh'),
    'bgr': ('Bulgaria', 'Bulgária'),
    'bhr': ('Bahrain', 'Barein'),
    'bhs': ('Bahamas', 'Bahamas'),
    'bih': ('Bosnia and Herzegovina', 'Bósnia e Herzegovina'),
    'blm': ('Saint Barthélemy', 'São Bartolomeu'),
    'blr': ('Belarus', 'Bielorrússia'),
    'blz': ('Belize', 'Belize'),
    'bmu': ('Bermuda', 'Bermudas'),
    'bol': ('Bolivia', 'Bolívia'),
    'bra': ('Brazil', 'Brasil'),
    'brb': ('Barbados', 'Barbados'),
    'brn': ('Brunei Darussalam', 'Brunei'),
    'btn': ('Bhutan', 'Butão'),
    'bvt': ('Bouvet Island', 'Ilha Bouvet'),
    'bwa': ('Botswana', 'Botsuana'),
    'caf': ('Central African Republic', 'República Centro-Africana'),
    'can': ('Canada', 'Canadá'),
    'cck': ('Cocos (Keeling) Islands', 'Ilhas Cocos (Keeling)'),
    'che': ('Switzerland', 'Suíça'),
    'chl': ('Chile', 'Chile'),
    'chn': ('China', 'China'),
    'civ': ("Côte d'Ivoire", 'Costa do Marfim'),
    'cmr': ('Cameroon', 'Camarões'),
    'cod': ('Congo, The Democratic Republic of the', 'Congo - Kinshasa'),
    'cog': ('Congo', 'República do Congo'),
    'cok': ('Cook Islands', 'Ilhas Cook'),
    'col': ('Colombia', 'Colômbia'),
    'com': ('Comoros', 'Comores'),
    'cpv': ('Cabo Verde', 'Cabo Verde'),
    'cri': ('Costa Rica', 'Costa Rica'),
    'cub': ('Cuba', 'Cuba'),
    'cuw': ('Curaçao', 'Curaçao'),
    'cxr': ('Christmas Island', 'Ilha Christmas'),
    'cym': ('Cayman Islands', 'Ilhas Cayman'),
    'cyp': ('Cyprus', 'Chipre'),
    'cze': ('Czechia', 'Tchéquia'),
    'deu': ('Germany', 'Alemanha'),
    'dji': ('Djibouti', 'Djibuti'),
    'dma': ('Dominica', 'Dominica'),
    'dnk': ('Denmark', 'Dinamarca'),
    'dom': ('Dominican Republic', 'República Dominicana'),
    'dza': ('Algeria', 'Argélia'),
    'ecu': ('Ecuador', 'Equador'),
    'egy': ('Egypt', 'Egito'),
    'eri': ('Eritrea', 'Eritreia'),
    'esh': ('Western Sahara', 'Saara Ocidental'),
    'esp': ('Spain', 'Espanha'),
    'est': ('Estonia', 'Estônia'),
    'eth': ('Ethiopia', 'Etiópia'),
    'fin': ('Finland', 'Finlândia'),
    'fji': ('Fiji', 'Fiji'),
    'flk': ('Falkland Islands (Malvinas)', 'Ilhas Malvinas'),
    'fra': ('France', 'França'),
    'fro': ('Faroe Islands', 'Ilhas Faroé'),
    'fsm': ('Micronesia, Federated States of', 'Micronésia'),
    'gab': ('Gabon', 'Gabão'),
    'gbr': ('United Kingdom', 'Reino Unido'),
    'geo': ('Georgia', 'Geórgia'),
    'ggy': ('Guernsey', 'Guernsey'),
    'gha': ('Ghana', 'Gana'),
    'gib': ('Gibraltar', 'Gibraltar'),
    'gin': ('Guinea', 'Guiné'),
    'glp': ('Guadeloupe', 'Guadalupe'),
    'gmb': ('Gambia', 'Gâmbia'),
    'gnb': ('Guinea-Bissau', 'Guiné-Bissau'),
    'gnq': ('Equatorial Guinea', 'Guiné Equatorial'),
    'grc': ('Greece', 'Grécia'),
    'grd': ('Grenada', 'Granada'),
    'grl': ('Greenland', 'Groenlândia'),
    'gtm': ('Guatemala', 'Guatemala'),
    'guf': ('French Guiana', 'Guiana Francesa'),
    'gum': ('Guam', 'Guam'),
    'guy': ('Guyana', 'Guiana'),
    'hkg': ('Hong Kong', 'Hong Kong, RAE da China'),
    'hmd': ('Heard Island and McDonald Islands', 'Ilhas Heard e McDonald'),
    'hnd': ('Honduras', 'Honduras'),
    'hrv': ('Croatia', 'Croácia'),
    'hti': ('Haiti', 'Haiti'),
    'hun': ('Hungary', 'Hungria'),
    'idn': ('Indonesia', 'Indonésia'),
    'imn': ('Isle of Man', 'Ilha de Man'),
    'ind': ('India', 'Índia'),
    'iot': ('British Indian Ocean Territory', 'Território Britânico do Oceano Índico'),
    'irl': ('Ireland', 'Irlanda'),
    'irn': ('Iran', 'Irã'),
    'irq': ('Iraq', 'Iraque'),
    'isl': ('Iceland', 'Islândia'),
    'isr': ('Israel', 'Israel'),
    'ita': ('Italy', 'Itália'),
    'jam': ('Jamaica', 'Jamaica'),
    'jey': ('Jersey', 'Jersey'),
    'jor': ('Jordan', 'Jordânia'),
    'jpn': ('Japan', 'Japão'),
    'kaz': ('Kazakhstan', 'Cazaquistão'),
    'ken': ('Kenya', 'Quênia'),
    'kgz': ('Kyrgyzstan', 'Quirguistão'),
    'khm': ('Cambodia', 'Camboja'),
    'kir': ('Kiribati', 'Quiribati'),
    'kna': ('Saint Kitts and Nevis', 'São Cristóvão e Névis'),
    'kor': ('South Korea', 'Coreia do Sul'),
    'kwt': ('Kuwait', 'Kuwait'),
    'lao': ('Laos', 'Laos'),
    'lbn': ('Lebanon', 'Líbano'),
    'lbr': ('Liberia', 'Libéria'),
    'lby': ('Libya', 'Líbia'),
    'lca': ('Saint Lucia', 'Santa Lúcia'),
    'lie': ('Liechtenstein', 'Liechtenstein'),
    'lka': ('Sri Lanka', 'Sri Lanka'),
    'lso': ('Lesotho', 'Lesoto'),
    'ltu': ('Lithuania', 'Lituânia'),
    'lux': ('Luxembourg', 'Luxemburgo'),
    'lva': ('Latvia', 'Letônia'),
    'mac': ('Macao', 'Macau, RAE da China'),
    'maf': ('Saint Martin (French part)', 'São Martinho'),
    'mar': ('Morocco', 'Marrocos'),
    'mco': ('Monaco', 'Mônaco'),
    'mda': ('Moldova', 'Moldávia'),
    'mdg': ('Madagascar', 'Madagascar'),
    'mdv': ('Maldives', 'Maldivas'),
    'mex': ('Mexico', 'México'),
    'mhl': ('Marshall Islands', 'Ilhas Marshall'),
    'mkd': ('North Macedonia', 'Macedônia do Norte'),
    'mli': ('Mali', 'Mali'),
    'mlt': ('Malta', 'Malta'),
    'mmr': ('Myanmar', 'Mianmar (Birmânia)'),
    'mne': ('Montenegro', 'Montenegro'),
    'mng': ('Mongolia', 'Mongólia'),
    'mnp': ('Northern Mariana Islands', 'Ilhas Marianas do Norte'),
    'moz': ('Mozambique', 'Moçambique'),
    'mrt': ('Mauritania', 'Mauritânia'),
    'msr': ('Montserrat', 'Montserrat'),
    'mtq': ('Martinique', 'Martinica'),
    'mus': ('Mauritius', 'Maurício'),
    'mwi': ('Malawi', 'Malaui'),
    'mys': ('Malaysia', 'Malásia'),
    'myt': ('Mayotte', 'Mayotte'),
    'nam': ('Namibia', 'Namíbia'),
    'ncl': ('New Caledonia', 'Nova Caledônia'),
    'ner': ('Niger', 'Níger'),
    'nfk': ('Norfolk Island', 'Ilha Norfolk'),
    'nga': ('Nigeria', 'Nigéria'),
    'nic': ('Nicaragua', 'Nicarágua'),
    'niu': ('Niue', 'Niue'),
    'nld': ('Netherlands', 'Países Baixos'),
    'nor': ('Norway', 'Noruega'),
    'npl': ('Nepal', 'Nepal'),
    'nru': ('Nauru', 'Nauru'),
    'nzl': ('New Zealand', 'Nova Zelândia'),
    'omn': ('Oman', 'Omã'),
    'pak': ('Pakistan', 'Paquistão'),
    'pan': ('Panama', 'Panamá'),
    'pcn': ('Pitcairn', 'Ilhas Pitcairn'),
    'per': ('Peru', 'Peru'),
    'phl': ('Philippines', 'Filipinas'),
    'plw': ('Palau', 'Palau'),
    'png': ('Papua New Guinea', 'Papua-Nova Guiné'),
    'pol': ('Poland', 'Polônia'),
    'pri': ('Puerto Rico', 'Porto Rico'),
    'prk': ('North Korea', 'Coreia do Norte'),
    'prt': ('Portugal', 'Portugal'),
    'pry': ('Paraguay', 'Paraguai'),
    'pse': ('Palestine, State of', 'Territórios palestinos'),
    'pyf': ('French Polynesia', 'Polinésia Francesa'),
    'qat': ('Qatar', 'Catar'),
    'reu': ('Réunion', 'Reunião'),
    'rou': ('Romania', 'Romênia'),
    'rus': ('Russian Federation', 'Rússia'),
    'rwa': ('Rwanda', 'Ruanda'),
    'sau': ('Saudi Arabia', 'Arábia Saudita'),
    'sdn': ('Sudan', 'Sudão'),
    'sen': ('Senegal', 'Senegal'),
    'sgp': ('Singapore', 'Singapura'),
    'sgs': ('South Georgia and the South Sandwich Islands', 'Ilhas Geórgia do Sul e Sandwich do Sul'),
    'shn': ('Saint Helena, Ascension and Tristan da Cunha', 'Santa Helena'),
    'sjm': ('Svalbard and Jan Mayen', 'Svalbard e Jan Mayen'),
    'slb': ('Solomon Islands', 'Ilhas Salomão'),
    'sle': ('Sierra Leone', 'Serra Leoa'),
    'slv': ('El Salvador', 'El Salvador'),
    'smr': ('San Marino', 'San Marino'),
    'som': ('Somalia', 'Somália'),
    'spm': ('Saint Pierre and Miquelon', 'São Pedro e Miquelão'),
    'srb': ('Serbia', 'Sérvia'),
    'ssd': ('South Sudan', 'Sudão do Sul'),
    'stp': ('Sao Tome and Principe', 'São Tomé e Príncipe'),
    'sur': ('Suriname', 'Suriname'),
    'svk': ('Slovakia', 'Eslováquia'),
    'svn': ('Slovenia', 'Eslovênia'),
    'swe': ('Sweden', 'Suécia'),
    'swz': ('Eswatini', 'Essuatíni'),
    'sxm': ('Sint Maarten (Dutch part)', 'Sint Maarten'),
    'syc': ('Seychelles', 'Seicheles'),
    'syr': ('Syria', 'Síria'),
    'tca': ('Turks and Caicos Islands', 'Ilhas Turcas e Caicos'),
    'tcd': ('Chad', 'Chade'),
    'tgo': ('Togo', 'Togo'),
    'tha': ('Thailand', 'Tailândia'),
    'tjk': ('Tajikistan', 'Tadjiquistão'),
    'tkl': ('Tokelau', 'Tokelau'),
    'tkm': ('Turkmenistan', 'Turcomenistão'),
    'tls': ('Timor-Leste', 'Timor-Leste'),
    'ton': ('Tonga', 'Tonga'),
    'tto': ('Trinidad and Tobago', 'Trinidad e Tobago'),
    'tun': ('Tunisia', 'Tunísia'),
    'tur': ('Türkiye', 'Turquia'),
    'tuv': ('Tuvalu', 'Tuvalu'),
    'twn': ('Taiwan', 'Taiwan'),
    'tza': ('Tanzania', 'Tanzânia'),
    'uga': ('Uganda', 'Uganda'),
    'ukr': ('Ukraine', 'Ucrânia'),
    'umi': ('United States Minor Outlying Islands', 'Ilhas Menores Distantes dos EUA'),
    'ury': ('Uruguay', 'Uruguai'),
    'usa': ('United States', 'Estados Unidos'),
    'uzb': ('Uzbekistan', 'Uzbequistão'),
    'vat': ('Holy See (Vatican City State)', 'Cidade do Vaticano'),
    'vct': ('Saint Vincent and the Grenadines', 'São Vicente e Granadinas'),
    'ven': ('Venezuela', 'Venezuela'),
    'vgb': ('Virgin Islands, British', 'Ilhas Virgens Britânicas'),
    'vir': ('Virgin Islands, U.S.', 'Ilhas Virgens Americanas'),
    'vnm': ('Vietnam', 'Vietnã'),
    'vut': ('Vanuatu', 'Vanuatu'),
    'wlf': ('Wallis and Futuna', 'Wallis e Futuna'),
    'wsm': ('Samoa', 'Samoa'),
    'yem': ('Yemen', 'Iêmen'),
    'zaf': ('South Africa', 'África do Sul'),
    'zmb': ('Zambia', 'Zâmbia'),
    'zwe': ('Zimbabwe', 'Zimbábue'),
}

# Código numérico ISO 3166-1, que é o identificador usado pelo mapa do D3 (world-atlas).
NUMERICO = {
    'abw': '533',
    'afg': '004',
    'ago': '024',
    'aia': '660',
    'ala': '248',
    'alb': '008',
    'and': '020',
    'are': '784',
    'arg': '032',
    'arm': '051',
    'asm': '016',
    'ata': '010',
    'atf': '260',
    'atg': '028',
    'aus': '036',
    'aut': '040',
    'aze': '031',
    'bdi': '108',
    'bel': '056',
    'ben': '204',
    'bes': '535',
    'bfa': '854',
    'bgd': '050',
    'bgr': '100',
    'bhr': '048',
    'bhs': '044',
    'bih': '070',
    'blm': '652',
    'blr': '112',
    'blz': '084',
    'bmu': '060',
    'bol': '068',
    'bra': '076',
    'brb': '052',
    'brn': '096',
    'btn': '064',
    'bvt': '074',
    'bwa': '072',
    'caf': '140',
    'can': '124',
    'cck': '166',
    'che': '756',
    'chl': '152',
    'chn': '156',
    'civ': '384',
    'cmr': '120',
    'cod': '180',
    'cog': '178',
    'cok': '184',
    'col': '170',
    'com': '174',
    'cpv': '132',
    'cri': '188',
    'cub': '192',
    'cuw': '531',
    'cxr': '162',
    'cym': '136',
    'cyp': '196',
    'cze': '203',
    'deu': '276',
    'dji': '262',
    'dma': '212',
    'dnk': '208',
    'dom': '214',
    'dza': '012',
    'ecu': '218',
    'egy': '818',
    'eri': '232',
    'esh': '732',
    'esp': '724',
    'est': '233',
    'eth': '231',
    'fin': '246',
    'fji': '242',
    'flk': '238',
    'fra': '250',
    'fro': '234',
    'fsm': '583',
    'gab': '266',
    'gbr': '826',
    'geo': '268',
    'ggy': '831',
    'gha': '288',
    'gib': '292',
    'gin': '324',
    'glp': '312',
    'gmb': '270',
    'gnb': '624',
    'gnq': '226',
    'grc': '300',
    'grd': '308',
    'grl': '304',
    'gtm': '320',
    'guf': '254',
    'gum': '316',
    'guy': '328',
    'hkg': '344',
    'hmd': '334',
    'hnd': '340',
    'hrv': '191',
    'hti': '332',
    'hun': '348',
    'idn': '360',
    'imn': '833',
    'ind': '356',
    'iot': '086',
    'irl': '372',
    'irn': '364',
    'irq': '368',
    'isl': '352',
    'isr': '376',
    'ita': '380',
    'jam': '388',
    'jey': '832',
    'jor': '400',
    'jpn': '392',
    'kaz': '398',
    'ken': '404',
    'kgz': '417',
    'khm': '116',
    'kir': '296',
    'kna': '659',
    'kor': '410',
    'kwt': '414',
    'lao': '418',
    'lbn': '422',
    'lbr': '430',
    'lby': '434',
    'lca': '662',
    'lie': '438',
    'lka': '144',
    'lso': '426',
    'ltu': '440',
    'lux': '442',
    'lva': '428',
    'mac': '446',
    'maf': '663',
    'mar': '504',
    'mco': '492',
    'mda': '498',
    'mdg': '450',
    'mdv': '462',
    'mex': '484',
    'mhl': '584',
    'mkd': '807',
    'mli': '466',
    'mlt': '470',
    'mmr': '104',
    'mne': '499',
    'mng': '496',
    'mnp': '580',
    'moz': '508',
    'mrt': '478',
    'msr': '500',
    'mtq': '474',
    'mus': '480',
    'mwi': '454',
    'mys': '458',
    'myt': '175',
    'nam': '516',
    'ncl': '540',
    'ner': '562',
    'nfk': '574',
    'nga': '566',
    'nic': '558',
    'niu': '570',
    'nld': '528',
    'nor': '578',
    'npl': '524',
    'nru': '520',
    'nzl': '554',
    'omn': '512',
    'pak': '586',
    'pan': '591',
    'pcn': '612',
    'per': '604',
    'phl': '608',
    'plw': '585',
    'png': '598',
    'pol': '616',
    'pri': '630',
    'prk': '408',
    'prt': '620',
    'pry': '600',
    'pse': '275',
    'pyf': '258',
    'qat': '634',
    'reu': '638',
    'rou': '642',
    'rus': '643',
    'rwa': '646',
    'sau': '682',
    'sdn': '729',
    'sen': '686',
    'sgp': '702',
    'sgs': '239',
    'shn': '654',
    'sjm': '744',
    'slb': '090',
    'sle': '694',
    'slv': '222',
    'smr': '674',
    'som': '706',
    'spm': '666',
    'srb': '688',
    'ssd': '728',
    'stp': '678',
    'sur': '740',
    'svk': '703',
    'svn': '705',
    'swe': '752',
    'swz': '748',
    'sxm': '534',
    'syc': '690',
    'syr': '760',
    'tca': '796',
    'tcd': '148',
    'tgo': '768',
    'tha': '764',
    'tjk': '762',
    'tkl': '772',
    'tkm': '795',
    'tls': '626',
    'ton': '776',
    'tto': '780',
    'tun': '788',
    'tur': '792',
    'tuv': '798',
    'twn': '158',
    'tza': '834',
    'uga': '800',
    'ukr': '804',
    'umi': '581',
    'ury': '858',
    'usa': '840',
    'uzb': '860',
    'vat': '336',
    'vct': '670',
    'ven': '862',
    'vgb': '092',
    'vir': '850',
    'vnm': '704',
    'vut': '548',
    'wlf': '876',
    'wsm': '882',
    'yem': '887',
    'zaf': '710',
    'zmb': '894',
    'zwe': '716',
}
